{{- if .Values.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeseer.metricsServiceName" . }}
  namespace: {{ include "kubeseer.namespace" . }}
  labels:
    {{- include "kubeseer.labels" . | nindent 4 }}
  annotations:
    {{- include "kubeseer.ownershipAnnotations" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "kubeseer.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
{{- end }}
