apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeseer.fullname" . }}-package
  namespace: {{ include "kubeseer.namespace" . }}
  labels:
    {{- include "kubeseer.labels" . | nindent 4 }}
  annotations:
    {{- include "kubeseer.ownershipAnnotations" . | nindent 4 }}
data:
  chart-version: {{ .Chart.Version | quote }}
  app-version: {{ .Chart.AppVersion | quote }}
  crd-kubeseer-sha256: {{ index .Chart.Annotations "kubeseer.io/generated-crd-kubeseer-sha256" | quote }}
  crd-access-policy-sha256: {{ index .Chart.Annotations "kubeseer.io/generated-crd-access-policy-sha256" | quote }}
  certificate-mode: {{ .Values.certificate.mode | quote }}
