apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeseer.serviceAccountName" . }}
  namespace: {{ include "kubeseer.namespace" . }}
  labels:
    {{- include "kubeseer.labels" . | nindent 4 }}
  annotations:
    {{- include "kubeseer.ownershipAnnotations" . | nindent 4 }}
automountServiceAccountToken: true
