apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeseer.webhookServiceName" . }}
  namespace: {{ include "kubeseer.namespace" . }}
  labels:
    {{- include "kubeseer.labels" . | nindent 4 }}
  annotations:
    {{- include "kubeseer.ownershipAnnotations" . | nindent 4 }}
spec:
  type: ClusterIP
  publishNotReadyAddresses: false
  selector:
    {{- include "kubeseer.selectorLabels" . | nindent 4 }}
  ports:
    - name: https-webhook
      port: 443
      targetPort: webhook
      protocol: TCP
