# Copyright 2026 Alessandro Rontani
# Licensed under the Apache License, Version 2.0.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: widgets.fixtures.kubeseer.io
  labels: {kubeseer.io/example: custom-resource}
spec:
  group: fixtures.kubeseer.io
  scope: Namespaced
  names: {plural: widgets, singular: widget, kind: Widget, listKind: WidgetList}
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties: {size: {type: integer}}
