# Copyright 2026 Alessandro Rontani
# Licensed under the Apache License, Version 2.0.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: kubeseer-example-operator
  labels:
    kubeseer.io/example: value-operator
    app.kubernetes.io/name: kubeseer-example-operator
spec:
  replicas: 3
  selector: {matchLabels: {app.kubernetes.io/name: kubeseer-example-operator}}
  template:
    metadata:
      labels: {app.kubernetes.io/name: kubeseer-example-operator, kubeseer.io/example: value-operator}
    spec:
      containers: [{name: fixture, image: registry.k8s.io/pause:3.10, imagePullPolicy: IfNotPresent}]
